<?php
/**
 * DefaultApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Ship24\TrackingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship24 Tracking API
 *
 * ## Getting started  Make sure to read the [Getting started](https://docs.ship24.com/getting-started) section of our [API Documentation](https://docs.ship24.com/) before using the endpoints presented below. ## Documentation structure  Use the top navigation bar to switch from:  - Our [API Documentation](https://docs.ship24.com/), which contains a comprehensive explanation of how our API works. - Our [API Reference](https://docs.ship24.com/tracking-api-reference/), which contains the specification of each of our endpoints. - Our [Support](https://docs.ship24.com/support/introduction) section, which contains help articles for most of the common questions and issues you may encounter.  ## Import our documentation into your HTTP client  Our API Reference is available as an Open API 3.1 format file, which is supported by most HTTP clients.  - Latest version: https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml  | <!-- -->                                                     | <!-- -->                                                                                                                                                     | | ------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | | ![Postman](/img/postman-logo.svg) Postman                    | In Postman, click on \"Import\", go on the \"Link\" tab, and paste this URL `https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml`                           | | <img src=\"/img/insomnia-logo.png\" width=\"32\"></img> Insomnia | From Insomnia preferences, locate the \"Import data\" option, choose \"From URL\", and paste this URL `https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml` |
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ship24\TrackingApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Ship24\TrackingApi\ApiException;
use Ship24\TrackingApi\Configuration;
use Ship24\TrackingApi\HeaderSelector;
use Ship24\TrackingApi\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  Ship24\TrackingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'receiveWebhooksHealthCheck' => [
            'application/json',
        ],
        'receiveWebhooksTrackingResults' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation receiveWebhooksHealthCheck
     *
     * Receive webhooks - Health check
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksHealthCheck'] to see the possible values for this operation
     *
     * @throws \Ship24\TrackingApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function receiveWebhooksHealthCheck($authorization = null, string $contentType = self::contentTypes['receiveWebhooksHealthCheck'][0])
    {
        $this->receiveWebhooksHealthCheckWithHttpInfo($authorization, $contentType);
    }

    /**
     * Operation receiveWebhooksHealthCheckWithHttpInfo
     *
     * Receive webhooks - Health check
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksHealthCheck'] to see the possible values for this operation
     *
     * @throws \Ship24\TrackingApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function receiveWebhooksHealthCheckWithHttpInfo($authorization = null, string $contentType = self::contentTypes['receiveWebhooksHealthCheck'][0])
    {
        $request = $this->receiveWebhooksHealthCheckRequest($authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation receiveWebhooksHealthCheckAsync
     *
     * Receive webhooks - Health check
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveWebhooksHealthCheckAsync($authorization = null, string $contentType = self::contentTypes['receiveWebhooksHealthCheck'][0])
    {
        return $this->receiveWebhooksHealthCheckAsyncWithHttpInfo($authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation receiveWebhooksHealthCheckAsyncWithHttpInfo
     *
     * Receive webhooks - Health check
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveWebhooksHealthCheckAsyncWithHttpInfo($authorization = null, string $contentType = self::contentTypes['receiveWebhooksHealthCheck'][0])
    {
        $returnType = '';
        $request = $this->receiveWebhooksHealthCheckRequest($authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'receiveWebhooksHealthCheck'
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksHealthCheck'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function receiveWebhooksHealthCheckRequest($authorization = null, string $contentType = self::contentTypes['receiveWebhooksHealthCheck'][0])
    {



        $resourcePath = '/your-endpoint';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'HEAD',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation receiveWebhooksTrackingResults
     *
     * Receive webhooks - Tracking results
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  \Ship24\TrackingApi\Model\ReceiveWebhooksTrackingResultsRequest|null $receive_webhooks_tracking_results_request Ship24 will send the following JSON body: (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksTrackingResults'] to see the possible values for this operation
     *
     * @throws \Ship24\TrackingApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function receiveWebhooksTrackingResults($authorization = null, $receive_webhooks_tracking_results_request = null, string $contentType = self::contentTypes['receiveWebhooksTrackingResults'][0])
    {
        $this->receiveWebhooksTrackingResultsWithHttpInfo($authorization, $receive_webhooks_tracking_results_request, $contentType);
    }

    /**
     * Operation receiveWebhooksTrackingResultsWithHttpInfo
     *
     * Receive webhooks - Tracking results
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  \Ship24\TrackingApi\Model\ReceiveWebhooksTrackingResultsRequest|null $receive_webhooks_tracking_results_request Ship24 will send the following JSON body: (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksTrackingResults'] to see the possible values for this operation
     *
     * @throws \Ship24\TrackingApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function receiveWebhooksTrackingResultsWithHttpInfo($authorization = null, $receive_webhooks_tracking_results_request = null, string $contentType = self::contentTypes['receiveWebhooksTrackingResults'][0])
    {
        $request = $this->receiveWebhooksTrackingResultsRequest($authorization, $receive_webhooks_tracking_results_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation receiveWebhooksTrackingResultsAsync
     *
     * Receive webhooks - Tracking results
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  \Ship24\TrackingApi\Model\ReceiveWebhooksTrackingResultsRequest|null $receive_webhooks_tracking_results_request Ship24 will send the following JSON body: (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksTrackingResults'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveWebhooksTrackingResultsAsync($authorization = null, $receive_webhooks_tracking_results_request = null, string $contentType = self::contentTypes['receiveWebhooksTrackingResults'][0])
    {
        return $this->receiveWebhooksTrackingResultsAsyncWithHttpInfo($authorization, $receive_webhooks_tracking_results_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation receiveWebhooksTrackingResultsAsyncWithHttpInfo
     *
     * Receive webhooks - Tracking results
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  \Ship24\TrackingApi\Model\ReceiveWebhooksTrackingResultsRequest|null $receive_webhooks_tracking_results_request Ship24 will send the following JSON body: (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksTrackingResults'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveWebhooksTrackingResultsAsyncWithHttpInfo($authorization = null, $receive_webhooks_tracking_results_request = null, string $contentType = self::contentTypes['receiveWebhooksTrackingResults'][0])
    {
        $returnType = '';
        $request = $this->receiveWebhooksTrackingResultsRequest($authorization, $receive_webhooks_tracking_results_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'receiveWebhooksTrackingResults'
     *
     * @param  string|null $authorization Ship24 will send your allocated webhook secret in each request. (optional)
     * @param  \Ship24\TrackingApi\Model\ReceiveWebhooksTrackingResultsRequest|null $receive_webhooks_tracking_results_request Ship24 will send the following JSON body: (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['receiveWebhooksTrackingResults'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function receiveWebhooksTrackingResultsRequest($authorization = null, $receive_webhooks_tracking_results_request = null, string $contentType = self::contentTypes['receiveWebhooksTrackingResults'][0])
    {




        $resourcePath = '/your-endpoint';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($receive_webhooks_tracking_results_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($receive_webhooks_tracking_results_request));
            } else {
                $httpBody = $receive_webhooks_tracking_results_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
