<?php
/**
 * TrackerCreateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Ship24\TrackingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ship24 Tracking API
 *
 * ## Getting started  Make sure to read the [Getting started](https://docs.ship24.com/getting-started) section of our [API Documentation](https://docs.ship24.com/) before using the endpoints presented below. ## Documentation structure  Use the top navigation bar to switch from:  - Our [API Documentation](https://docs.ship24.com/), which contains a comprehensive explanation of how our API works. - Our [API Reference](https://docs.ship24.com/tracking-api-reference/), which contains the specification of each of our endpoints. - Our [Support](https://docs.ship24.com/support/introduction) section, which contains help articles for most of the common questions and issues you may encounter.  ## Import our documentation into your HTTP client  Our API Reference is available as an Open API 3.1 format file, which is supported by most HTTP clients.  - Latest version: https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml  | <!-- -->                                                     | <!-- -->                                                                                                                                                     | | ------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------ | | ![Postman](/img/postman-logo.svg) Postman                    | In Postman, click on \"Import\", go on the \"Link\" tab, and paste this URL `https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml`                           | | <img src=\"/img/insomnia-logo.png\" width=\"32\"></img> Insomnia | From Insomnia preferences, locate the \"Import data\" option, choose \"From URL\", and paste this URL `https://docs.ship24.com/assets/openapi/ship24-tracking-api.yaml` |
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ship24\TrackingApi\Model;

use \ArrayAccess;
use \Ship24\TrackingApi\ObjectSerializer;

/**
 * TrackerCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  Ship24\TrackingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrackerCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'tracker-create-request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tracking_number' => 'string',
        'shipment_reference' => 'string',
        'client_tracker_id' => 'string',
        'origin_country_code' => 'string',
        'destination_country_code' => 'string',
        'destination_post_code' => 'string',
        'shipping_date' => '\DateTime',
        'courier_code' => 'string[]',
        'courier_name' => 'string',
        'tracking_url' => 'string',
        'order_number' => 'string',
        'title' => 'string',
        'recipient' => '\Ship24\TrackingApi\Model\TrackerCreateRequestRecipient',
        'settings' => '\Ship24\TrackingApi\Model\TrackerCreateRequestSettings'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tracking_number' => null,
        'shipment_reference' => null,
        'client_tracker_id' => null,
        'origin_country_code' => 'ISO 3166-1 alpha-2/alpha-3',
        'destination_country_code' => 'ISO 3166-1 alpha-2/alpha-3',
        'destination_post_code' => null,
        'shipping_date' => 'date-time',
        'courier_code' => null,
        'courier_name' => null,
        'tracking_url' => null,
        'order_number' => null,
        'title' => null,
        'recipient' => null,
        'settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tracking_number' => false,
        'shipment_reference' => false,
        'client_tracker_id' => false,
        'origin_country_code' => false,
        'destination_country_code' => false,
        'destination_post_code' => false,
        'shipping_date' => false,
        'courier_code' => false,
        'courier_name' => false,
        'tracking_url' => false,
        'order_number' => false,
        'title' => false,
        'recipient' => false,
        'settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tracking_number' => 'trackingNumber',
        'shipment_reference' => 'shipmentReference',
        'client_tracker_id' => 'clientTrackerId',
        'origin_country_code' => 'originCountryCode',
        'destination_country_code' => 'destinationCountryCode',
        'destination_post_code' => 'destinationPostCode',
        'shipping_date' => 'shippingDate',
        'courier_code' => 'courierCode',
        'courier_name' => 'courierName',
        'tracking_url' => 'trackingUrl',
        'order_number' => 'orderNumber',
        'title' => 'title',
        'recipient' => 'recipient',
        'settings' => 'settings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tracking_number' => 'setTrackingNumber',
        'shipment_reference' => 'setShipmentReference',
        'client_tracker_id' => 'setClientTrackerId',
        'origin_country_code' => 'setOriginCountryCode',
        'destination_country_code' => 'setDestinationCountryCode',
        'destination_post_code' => 'setDestinationPostCode',
        'shipping_date' => 'setShippingDate',
        'courier_code' => 'setCourierCode',
        'courier_name' => 'setCourierName',
        'tracking_url' => 'setTrackingUrl',
        'order_number' => 'setOrderNumber',
        'title' => 'setTitle',
        'recipient' => 'setRecipient',
        'settings' => 'setSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tracking_number' => 'getTrackingNumber',
        'shipment_reference' => 'getShipmentReference',
        'client_tracker_id' => 'getClientTrackerId',
        'origin_country_code' => 'getOriginCountryCode',
        'destination_country_code' => 'getDestinationCountryCode',
        'destination_post_code' => 'getDestinationPostCode',
        'shipping_date' => 'getShippingDate',
        'courier_code' => 'getCourierCode',
        'courier_name' => 'getCourierName',
        'tracking_url' => 'getTrackingUrl',
        'order_number' => 'getOrderNumber',
        'title' => 'getTitle',
        'recipient' => 'getRecipient',
        'settings' => 'getSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tracking_number', $data ?? [], null);
        $this->setIfExists('shipment_reference', $data ?? [], null);
        $this->setIfExists('client_tracker_id', $data ?? [], null);
        $this->setIfExists('origin_country_code', $data ?? [], null);
        $this->setIfExists('destination_country_code', $data ?? [], null);
        $this->setIfExists('destination_post_code', $data ?? [], null);
        $this->setIfExists('shipping_date', $data ?? [], null);
        $this->setIfExists('courier_code', $data ?? [], null);
        $this->setIfExists('courier_name', $data ?? [], null);
        $this->setIfExists('tracking_url', $data ?? [], null);
        $this->setIfExists('order_number', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('recipient', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tracking_number'] === null) {
            $invalidProperties[] = "'tracking_number' can't be null";
        }
        if ((mb_strlen($this->container['tracking_number']) > 50)) {
            $invalidProperties[] = "invalid value for 'tracking_number', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['tracking_number']) < 5)) {
            $invalidProperties[] = "invalid value for 'tracking_number', the character length must be bigger than or equal to 5.";
        }

        if (!preg_match("/^[a-zA-Z0-9-_\/.]*$/", $this->container['tracking_number'])) {
            $invalidProperties[] = "invalid value for 'tracking_number', must be conform to the pattern /^[a-zA-Z0-9-_\/.]*$/.";
        }

        if (!is_null($this->container['courier_code']) && (count($this->container['courier_code']) > 3)) {
            $invalidProperties[] = "invalid value for 'courier_code', number of items must be less than or equal to 3.";
        }

        if (!is_null($this->container['courier_code']) && (count($this->container['courier_code']) < 0)) {
            $invalidProperties[] = "invalid value for 'courier_code', number of items must be greater than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tracking_number
     *
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->container['tracking_number'];
    }

    /**
     * Sets tracking_number
     *
     * @param string $tracking_number Tracking number of the shipment.
     *
     * @return self
     */
    public function setTrackingNumber($tracking_number)
    {
        if (is_null($tracking_number)) {
            throw new \InvalidArgumentException('non-nullable tracking_number cannot be null');
        }
        if ((mb_strlen($tracking_number) > 50)) {
            throw new \InvalidArgumentException('invalid length for $tracking_number when calling TrackerCreateRequest., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($tracking_number) < 5)) {
            throw new \InvalidArgumentException('invalid length for $tracking_number when calling TrackerCreateRequest., must be bigger than or equal to 5.');
        }
        if ((!preg_match("/^[a-zA-Z0-9-_\/.]*$/", ObjectSerializer::toString($tracking_number)))) {
            throw new \InvalidArgumentException("invalid value for \$tracking_number when calling TrackerCreateRequest., must conform to the pattern /^[a-zA-Z0-9-_\/.]*$/.");
        }

        $this->container['tracking_number'] = $tracking_number;

        return $this;
    }

    /**
     * Gets shipment_reference
     *
     * @return string|null
     */
    public function getShipmentReference()
    {
        return $this->container['shipment_reference'];
    }

    /**
     * Sets shipment_reference
     *
     * @param string|null $shipment_reference Your reference for this shipment. Will be provided in our webhooks or API responses for this tracker.
     *
     * @return self
     */
    public function setShipmentReference($shipment_reference)
    {
        if (is_null($shipment_reference)) {
            throw new \InvalidArgumentException('non-nullable shipment_reference cannot be null');
        }
        $this->container['shipment_reference'] = $shipment_reference;

        return $this;
    }

    /**
     * Gets client_tracker_id
     *
     * @return string|null
     */
    public function getClientTrackerId()
    {
        return $this->container['client_tracker_id'];
    }

    /**
     * Sets client_tracker_id
     *
     * @param string|null $client_tracker_id Your unique identifier for this shipment. Will be provided in our webhooks or API responses for this tracker.
     *
     * @return self
     */
    public function setClientTrackerId($client_tracker_id)
    {
        if (is_null($client_tracker_id)) {
            throw new \InvalidArgumentException('non-nullable client_tracker_id cannot be null');
        }
        $this->container['client_tracker_id'] = $client_tracker_id;

        return $this;
    }

    /**
     * Gets origin_country_code
     *
     * @return string|null
     */
    public function getOriginCountryCode()
    {
        return $this->container['origin_country_code'];
    }

    /**
     * Sets origin_country_code
     *
     * @param string|null $origin_country_code Sender country code.
     *
     * @return self
     */
    public function setOriginCountryCode($origin_country_code)
    {
        if (is_null($origin_country_code)) {
            throw new \InvalidArgumentException('non-nullable origin_country_code cannot be null');
        }
        $this->container['origin_country_code'] = $origin_country_code;

        return $this;
    }

    /**
     * Gets destination_country_code
     *
     * @return string|null
     */
    public function getDestinationCountryCode()
    {
        return $this->container['destination_country_code'];
    }

    /**
     * Sets destination_country_code
     *
     * @param string|null $destination_country_code Recipient country code - 📌 Recommended to improve tracking accuracy
     *
     * @return self
     */
    public function setDestinationCountryCode($destination_country_code)
    {
        if (is_null($destination_country_code)) {
            throw new \InvalidArgumentException('non-nullable destination_country_code cannot be null');
        }
        $this->container['destination_country_code'] = $destination_country_code;

        return $this;
    }

    /**
     * Gets destination_post_code
     *
     * @return string|null
     */
    public function getDestinationPostCode()
    {
        return $this->container['destination_post_code'];
    }

    /**
     * Sets destination_post_code
     *
     * @param string|null $destination_post_code Recipient Post code (or ZIP code)  - 📌 Recommended to improve tracking accuracy
     *
     * @return self
     */
    public function setDestinationPostCode($destination_post_code)
    {
        if (is_null($destination_post_code)) {
            throw new \InvalidArgumentException('non-nullable destination_post_code cannot be null');
        }
        $this->container['destination_post_code'] = $destination_post_code;

        return $this;
    }

    /**
     * Gets shipping_date
     *
     * @return \DateTime|null
     */
    public function getShippingDate()
    {
        return $this->container['shipping_date'];
    }

    /**
     * Sets shipping_date
     *
     * @param \DateTime|null $shipping_date Date at which the shipment has been shipped  - 📌 Recommended to improve tracking accuracy: providing the shipping date helps us accurately identify the shipment and improves our ability to retrieve the correct data. However, an inaccurate shipping date could cause our system to exclude the right shipment. Therefore, please ensure the provided shipping date aligns closely with the actual shipment date, give or take a few days. [Format](http://docs.ship24.com/data-format#logistics-date-and-time)
     *
     * @return self
     */
    public function setShippingDate($shipping_date)
    {
        if (is_null($shipping_date)) {
            throw new \InvalidArgumentException('non-nullable shipping_date cannot be null');
        }
        $this->container['shipping_date'] = $shipping_date;

        return $this;
    }

    /**
     * Gets courier_code
     *
     * @return string[]|null
     */
    public function getCourierCode()
    {
        return $this->container['courier_code'];
    }

    /**
     * Sets courier_code
     *
     * @param string[]|null $courier_code Code of the courier(s) handling the shipment (Up to 3 max) (see Couriers list section)  - 📌 Recommended to improve tracking accuracy
     *
     * @return self
     */
    public function setCourierCode($courier_code)
    {
        if (is_null($courier_code)) {
            throw new \InvalidArgumentException('non-nullable courier_code cannot be null');
        }

        if ((count($courier_code) > 3)) {
            throw new \InvalidArgumentException('invalid value for $courier_code when calling TrackerCreateRequest., number of items must be less than or equal to 3.');
        }
        if ((count($courier_code) < 0)) {
            throw new \InvalidArgumentException('invalid length for $courier_code when calling TrackerCreateRequest., number of items must be greater than or equal to 0.');
        }
        $this->container['courier_code'] = $courier_code;

        return $this;
    }

    /**
     * Gets courier_name
     *
     * @return string|null
     */
    public function getCourierName()
    {
        return $this->container['courier_name'];
    }

    /**
     * Sets courier_name
     *
     * @param string|null $courier_name Courier name and/or service.
     *
     * @return self
     */
    public function setCourierName($courier_name)
    {
        if (is_null($courier_name)) {
            throw new \InvalidArgumentException('non-nullable courier_name cannot be null');
        }
        $this->container['courier_name'] = $courier_name;

        return $this;
    }

    /**
     * Gets tracking_url
     *
     * @return string|null
     */
    public function getTrackingUrl()
    {
        return $this->container['tracking_url'];
    }

    /**
     * Sets tracking_url
     *
     * @param string|null $tracking_url Tracking URL of the courier.
     *
     * @return self
     */
    public function setTrackingUrl($tracking_url)
    {
        if (is_null($tracking_url)) {
            throw new \InvalidArgumentException('non-nullable tracking_url cannot be null');
        }
        $this->container['tracking_url'] = $tracking_url;

        return $this;
    }

    /**
     * Gets order_number
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     *
     * @param string|null $order_number Order number in case of an eCommerce order.
     *
     * @return self
     */
    public function setOrderNumber($order_number)
    {
        if (is_null($order_number)) {
            throw new \InvalidArgumentException('non-nullable order_number cannot be null');
        }
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Title for this shipment, visible on the Tracking Dashboard.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return \Ship24\TrackingApi\Model\TrackerCreateRequestRecipient|null
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param \Ship24\TrackingApi\Model\TrackerCreateRequestRecipient|null $recipient recipient
     *
     * @return self
     */
    public function setRecipient($recipient)
    {
        if (is_null($recipient)) {
            throw new \InvalidArgumentException('non-nullable recipient cannot be null');
        }
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \Ship24\TrackingApi\Model\TrackerCreateRequestSettings|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \Ship24\TrackingApi\Model\TrackerCreateRequestSettings|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            throw new \InvalidArgumentException('non-nullable settings cannot be null');
        }
        $this->container['settings'] = $settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


